apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  replicas: 3
  image:
    repository: pravega/zookeeper
    tag: 0.2.12
  storageType: persistence
  persistence:
    reclaimPolicy: Delete
    spec:
      storageClassName: "standard"
      resources:
        requests:
          storage: 20Gi
