apiVersion: v2
name: zookeeper-operator
description: Zookeeper Operator Helm chart for Kubernetes
version: 0.2.15
appVersion: 0.2.15
keywords:
- zookeeper
- storage
home: https://github.com/pravega/zookeeper-operator
icon: https://zookeeper.apache.org/images/zookeeper_small.gif
