## Default values for zookeeper-operator.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

global:
  # Lists the secrets you need to use to pull zookeeper-operator image from a private registry.
  imagePullSecrets: []
  # - private-registry-key

image:
  repository: pravega/zookeeper-operator
  tag: 0.2.12
  pullPolicy: IfNotPresent

## Install RBAC roles and bindings.
rbac:
  create: true

## Service account name and whether to create it.
serviceAccount:
  create: true
  name: zookeeper-operator
  ## Optionally specify an array of imagePullSecrets. Will override the global parameter if set
  # imagePullSecrets:

## Whether to create the CRD.
crd:
  create: true

## Specifies which namespace(s) the Operator should watch over.
## Default: An empty string means all namespaces.
## Multiple namespaces can be configured using a comma separated list of namespaces
watchNamespace: ""

## Operator pod resources
resources: {}
  # limits:
  #   cpu: 2
  #   memory: 256Mi
  # requests:
  #   cpu: 1
  #   memory: 128Mi

# Scheduling constraints
nodeSelector: {}
affinity: {}
tolerations: []

# Pod annotations
annotations: {}

hooks:
  backoffLimit: 10
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10
  ## Whether to create pre-delete hook which ensures that
  ## the operator cannot be deleted till the zookeeper cluster
  ## custom resources have been cleaned up
  delete: true

## Additional Sidecars Configuration.
additionalSidecars: {}
# - name: nginx
#   image: nginx:latest

## Additional Environment Variables.
additionalEnv: {}

## Additional volumes required for sidecars.
additionalVolumes: {}
# - name: volume1
#   emptyDir: {}
# - name: volume2
#   emptyDir: {}
