## Default values for zookeeper-operator.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

global:
  # Lists the secrets you need to use to pull zookeeper-operator image from a private registry.
  imagePullSecrets: []
  # - private-registry-key

image:
  repository: pravega/zookeeper-operator
  tag: 0.2.8
  pullPolicy: IfNotPresent

## Install RBAC roles and bindings.
rbac:
  create: true

## Service account name and whether to create it.
serviceAccount:
  create: true
  name: zookeeper-operator
  ## Optionally specify an array of imagePullSecrets. Will override the global parameter if set
  # imagePullSecrets:

## Whether to create the CRD.
crd:
  create: true

## Specifies which namespace the Operator should watch over.
## An empty string means all namespaces.
watchNamespace: ""

## Operator pod resources
resources: {}
  # limits:
  #   cpu: 2
  #   memory: 256Mi
  # requests:
  #   cpu: 1
  #   memory: 128Mi
