{{- $storageType := .Values.storageType | default "persistence" -}}
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: {{ template "zookeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "zookeeper.commonLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  image:
    repository: {{ .Values.image.repository }}
    tag: {{ .Values.image.tag }}
    pullPolicy: {{ .Values.image.pullPolicy }}
  {{- if .Values.domainName }}
  domainName: {{ .Values.domainName }}
  {{- end }}
  kubernetesClusterDomain: {{ default "cluster.local" .Values.kubernetesClusterDomain }}
  {{- if .Values.probes }}
  probes:
    {{- if .Values.probes.readiness }}
    readinessProbe:
      initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds | default 10 }}
      periodSeconds: {{ .Values.probes.readiness.periodSeconds | default 10 }}
      failureThreshold: {{ .Values.probes.readiness.failureThreshold | default 3}}
      successThreshold: {{ .Values.probes.readiness.successThreshold | default 1 }}
      timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds | default 10}}
    {{- end }}
    {{- if .Values.probes.liveness }}
    livenessProbe:
      initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds | default 10 }}
      periodSeconds: {{ .Values.probes.liveness.periodSeconds | default 10 }}
      failureThreshold: {{ .Values.probes.liveness.failureThreshold | default 3 }}
      timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds | default 10 }}
    {{- end }}
  {{- end }}
  {{- if .Values.containers }}
  containers:
{{ toYaml .Values.containers | indent 4 }}
  {{- end }}
  {{- if .Values.volumes }}
  volumes:
{{ toYaml .Values.volumes | indent 4 }}
  {{- end }}
  {{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 4 }}
  {{- end }}
  {{- if .Values.initContainers }}
  initContainers:
{{ toYaml .Values.initContainers| indent 4 }}
  {{- end }}
  {{- if .Values.labels }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
  {{- end }}
  {{- if .Values.ports }}
  ports:
{{ toYaml .Values.ports | indent 4 }}
  {{- end }}
  {{- if .Values.triggerRollingRestart }}
  triggerRollingRestart: {{ .Values.triggerRollingRestart }}
  {{- end }}
  pod:
    {{- if .Values.pod.labels }}
    labels:
{{ toYaml .Values.pod.labels | indent 6 }}
    {{- end }}
    {{- if .Values.pod.nodeSelector }}
    nodeSelector:
{{ toYaml .Values.pod.nodeSelector | indent 6 }}
    {{- end }}
    {{- if .Values.pod.affinity }}
    affinity:
{{ toYaml .Values.pod.affinity | indent 6 }}
    {{- end }}
    {{- if .Values.pod.resources }}
    resources:
{{ toYaml .Values.pod.resources | indent 6 }}
    {{- end }}
    {{- if .Values.pod.tolerations }}
    tolerations:
{{ toYaml .Values.pod.tolerations | indent 6 }}
    {{- end }}
    {{- if .Values.pod.env }}
    env:
{{ toYaml .Values.pod.env | indent 6 }}
    {{- end }}
    {{- if .Values.pod.annotations }}
    annotations:
{{ toYaml .Values.pod.annotations | indent 6 }}
    {{- end }}
    {{- if .Values.pod.securityContext }}
    securityContext:
{{ toYaml .Values.pod.securityContext | indent 6 }}
    {{- end }}
    {{- if .Values.pod.terminationGracePeriodSeconds }}
    terminationGracePeriodSeconds: {{ .Values.pod.terminationGracePeriodSeconds }}
    {{- end }}
    serviceAccountName: {{ default "zookeeper" .Values.pod.serviceAccountName }}
    {{- if .Values.pod.imagePullSecrets }}
    imagePullSecrets:
{{ toYaml .Values.pod.imagePullSecrets | indent 6 }}
    {{- end }}
  {{- if .Values.clientService }}
  clientService:
    {{- if .Values.clientService.annotations }}
    annotations:
{{ toYaml .Values.clientService.annotations | indent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.headlessService }}
  headlessService:
    {{- if .Values.headlessService.annotations }}
    annotations:
{{ toYaml .Values.headlessService.annotations | indent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.adminServerService }}
  adminServerService:
    {{- if .Values.adminServerService.annotations }}
    annotations:
{{ toYaml .Values.adminServerService.annotations | indent 6 }}
    {{- end }}
    {{- if .Values.adminServerService.external }}
    external: {{ .Values.adminServerService.external }}
    {{- end }}
  {{- end }}
  {{- if .Values.config }}
  config:
    {{- if .Values.config.initLimit }}
    initLimit: {{ .Values.config.initLimit }}
    {{- end }}
    {{- if .Values.config.tickTime }}
    tickTime: {{ .Values.config.tickTime }}
    {{- end }}
    {{- if .Values.config.syncLimit }}
    syncLimit: {{ .Values.config.syncLimit }}
    {{- end }}
    {{- if .Values.config.globalOutstandingLimit }}
    globalOutstandingLimit: {{ .Values.config.globalOutstandingLimit }}
    {{- end }}
    {{- if .Values.config.preAllocSize }}
    preAllocSize: {{ .Values.config.preAllocSize }}
    {{- end }}
    {{- if .Values.config.snapCount }}
    snapCount: {{ .Values.config.snapCount }}
    {{- end }}
    {{- if .Values.config.commitLogCount }}
    commitLogCount: {{ .Values.config.commitLogCount }}
    {{- end }}
    {{- if .Values.config.snapSizeLimitInKb }}
    snapSizeLimitInKb: {{ .Values.config.snapSizeLimitInKb }}
    {{- end }}
    {{- if .Values.config.maxCnxns }}
    maxCnxns: {{ .Values.config.maxCnxns }}
    {{- end }}
    {{- if .Values.config.maxClientCnxns }}
    maxClientCnxns: {{ .Values.config.maxClientCnxns }}
    {{- end }}
    {{- if .Values.config.minSessionTimeout }}
    minSessionTimeout: {{ .Values.config.minSessionTimeout }}
    {{- end }}
    {{- if .Values.config.maxSessionTimeout }}
    maxSessionTimeout: {{ .Values.config.maxSessionTimeout }}
    {{- end }}
    {{- if .Values.config.autoPurgeSnapRetainCount }}
    autoPurgeSnapRetainCount: {{ .Values.config.autoPurgeSnapRetainCount }}
    {{- end }}
    {{- if .Values.config.autoPurgePurgeInterval }}
    autoPurgePurgeInterval: {{ .Values.config.autoPurgePurgeInterval }}
    {{- end }}
    {{- if .Values.config.quorumListenOnAllIPs }}
    quorumListenOnAllIPs: {{ .Values.config.quorumListenOnAllIPs }}
    {{- end }}
    {{- if .Values.config.additionalConfig }}
    additionalConfig:
    {{- toYaml .Values.config.additionalConfig | nindent 6 }}
    {{- end }}
  {{- end }}
  storageType: {{ $storageType }}
  {{- if eq $storageType "ephemeral" }}
  ephemeral:
    {{- if .Values.ephemeral.emptydirvolumesource }}
    emptydirvolumesource:
      {{- if .Values.ephemeral.emptydirvolumesource.medium }}
      medium: {{ .Values.ephemeral.emptydirvolumesource.medium }}
      {{- end }}
      {{- if .Values.ephemeral.emptydirvolumesource.sizeLimit }}
      sizeLimit: {{ .Values.ephemeral.emptydirvolumesource.sizeLimit }}
      {{- end }}
    {{- end }}
  {{- else }}
  persistence:
    reclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
    {{- if .Values.persistence.annotations }}
    annotations:
{{ toYaml .Values.persistence.annotations | indent 6 }}
    {{- end }}
    {{- if or .Values.persistence.storageClassName .Values.persistence.volumeSize }}
    spec:
      {{- if .Values.persistence.storageClassName }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      {{- end }}
      {{- if .Values.persistence.volumeSize }}
      resources:
        requests:
          storage: {{ .Values.persistence.volumeSize }}
      {{- end }}
    {{- end }}
  {{- end }}
