language: go
go:
- '1.13.8'
sudo: required
env:
    global:
      - KUBERNETES_VERSION=v1.15.0
      - OPERATOR_SDK_VERSION=v0.17.0
      - KUBERNETES_CONFIG_FILE=$HOME/.kube/config
      - CHANGE_MINIKUBE_NONE_USER=true
      - MINIKUBE_VERSION=v1.11.0
    secure: dIXvb2BS2AwvQf+McXNClqoV4AjobYyc0/2b+zn4yMQ2v8gAW5V0w8Y3af6EnwOLe9Szke0RRHj/5ktxyrnQtBLsQhZd13GUItLuvIyD1fZZx9/djA7aII71fqKBVLVg2OR9VFltfPDB1B9NSPD3w4NJhyWdAzUORnqiNkQmOc+WGdCVYJ6olXZoq1rCVD+ysxssuWaHVD4ujbdLmwToFhQiGGbpdInZjdLUZ8FWLEJHl5uHkntrHESDBBjZ+ZHeF5jZYEUKjoV0xvapiI+lqp6mcWzaVkop78SbjlHnbQNjqH3mW6i0lI7dRyMPPURUBPNKvhvDlAbRjd7CU70ASJmI2rCgKQru5tfASaegeCzdGCp1fOn4bdvDgL+9NtxsojL6J4j5H9MPmSE6zZVLLQN/wA4IM7vB12o+O7pEM40WiZ7qtCsolIFWE53zx9Beuf7FQFv8Zz/pCfUctvZdyE53T41uuzZVQC+w+w5sj/1rrLgBCjPD1ghNZdN+y3GD7Sgaic03a+FiCTKnOOab9Dk6Pil0m4qbYLJdkKKLt/PvAw7nb9GEX36VPLWrG9xCXsJvzbiG+JQBYEpSQrzJYj9vuNScoWZuvu1I+cRIZsj26dPt9XXn2I/8uQSKBQlNzPAIOD1NCTLtRglVkgPf+BxNppTLV2BmBRQ4V9ZtpJQ=
services:
- docker
install:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBERNETES_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBE_VERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/$OPERATOR_SDK_VERSION/operator-sdk-$OPERATOR_SDK_VERSION-x86_64-linux-gnu && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin/
before_script:
  - sudo mount --make-rshared /
  - sudo minikube start --vm-driver=none --bootstrapper=kubeadm --kubernetes-version=$KUBERNETES_VERSION
  - minikube update-context
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
  # Show cluster information
  - kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
  - kubectl cluster-info
  - kubectl -n kube-system get pod -o wide
script:
- make check
- make test
# ping stdout every 5 minutes or Travis kills build
# ref: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
- while sleep 5m; do kubectl get pods; done &
- echo "$TRAVIS_PULL_REQUEST"
- if [[ $TRAVIS_PULL_REQUEST != 'false' ]]; then make test-e2e; fi
# kill background echo loop
- echo "killing while sleep loop" && kill %1
- make clean
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: make push
    on:
      branch: master
      tags: true
  - provider: releases
    file:
      - bin/zookeeper-exporter-linux-amd64
      - bin/zookeeper-exporter-darwin-amd64
      - bin/zookeeper-exporter-windows-amd64.exe
    skip_cleanup: true
    on:
      branch: master
      tags: true
    api-key:
      secure: OCxUUA41MZ3PUAOjLwhup5o3pbved8uX8O3HRqfKnuKw+a++GuPXgdoFzzAdTfBSnemkDFvZ5SWYwp/08YfK1tKSI23PCyl65I8hORNFp5+MMkGcqZ8bCVk0Y59/lmhPS3hUPQM5F9WnuL8bys37c1h4zzAb4Y9FNHF63KzCedoD6QO0/zhghhxc51b4u8rHMC24SztAFlCJsBkdrda1XJpIB3hKh4ZsDBaRcTYbbQyh6g3vNRdjtmWOcsuxHz2O8tN1SSQAqwqfnPy6bpENGY/tUQc6qzDAAix2ls5yd4DC8ALBEH//lsGaf1cw9hot8CNl8TOKFvu03Y3p34EOLCWwYrvXX8p76c9JiyGtON8tc49+orQhdtaLOfSQiVhIO7wvQQDRkFetvuMCSSDLxAXSn8PCXYp0OXl3mlgB2xkrPr9TSbV2RfTbk+oZY6uBmFOrACp9a37/0JcuAItpEvzCb/jxdBMtEdNatlCbsvmbe/MYwNAW3RnI31wBY4EkYu4+r4Jm8MbHXNVGLTcJIiyZHmMEBh6SYR4gwiAEPYau2jhqpg27j0204V+gCyjoS+X1nNpU2tVpG8TPL14LJaVYI/eowYUkf0Yp6u5cOnV14iTyLHKRVoy2nzErxRLtmx4808F5r/N4noFfdNdnfhEJGNJD8oRtACjBVtBV/FU=
