apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper
  namespace: default
spec:
  # Add fields here
  replicas: 3
  image:
    repository: pravega/zookeeper
    tag: 0.2.7
  persistence:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    reclaimPolicy: Delete
    resources:
      requests:
        storage: 10Gi
