apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zookeeper-clusters.zookeeper.pravega.io
spec:
  group: zookeeper.pravega.io
  names:
    kind: ZookeeperCluster
    listKind: ZookeeperClusterList
    plural: zookeeper-clusters
    singular: zookeeper-cluster
  scope: Namespaced
  version: v1beta1
