apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zookeeper-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "zookeeper-operator.commonLabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "zookeeper-operator.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "zookeeper-operator.fullname" . }}
        component: zookeeper-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ template "zookeeper-operator.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 6000
          name: metrics
        command:
        - zookeeper-operator
        env:
        - name: WATCH_NAMESPACE
          value: "{{ .Values.watchNamespace }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: {{ template "zookeeper-operator.fullname" . }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
