replicas: 3

image:
  repository: pravega/zookeeper
  tag: 0.2.9
  pullPolicy: IfNotPresent

domainName:
labels: {}
ports: []
kubernetesClusterDomain: "cluster.local"

pod:
  # labels: {}
  # nodeSelector: {}
  # affinity: {}
  # resources: {}
  # tolerations: []
  # env: []
  # annotations: {}
  # securityContext: {}
  # terminationGracePeriodSeconds: 30
  serviceAccountName: zookeeper

config: {}
  # initLimit: 10
  # tickTime: 2000
  # syncLimit: 2
  # globalOutstandingLimit: 1000
  # preAllocSize: 65536
  # snapCount: 100000
  # commitLogCount: 500
  # snapSizeLimitInKb: 4194304
  # maxCnxns: 0
  # maxClientCnxns: 60
  # minSessionTimeout: 4000
  # maxSessionTimeout: 40000
  # autoPurgeSnapRetainCount: 3
  # autoPurgePurgeInterval: 1
  # quorumListenOnAllIPs: false

## configure the storage type
## accepted values : persistence/ephemeral
## default option is persistence
storageType: persistence

persistence:
  storageClassName:
  ## specifying reclaim policy for PersistentVolumes
  ## accepted values - Delete / Retain
  reclaimPolicy: Delete
  annotations: {}
  volumeSize: 20Gi

ephemeral:
  emptydirvolumesource:
    ## specifying Medium for emptydirvolumesource
    ## accepted values - ""/Memory
    medium: ""
    sizeLimit: 20Gi

hooks:
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10
  backoffLimit: 10

containers: []
volumes: []
