replicas: 3
maxUnavailableReplicas:

image:
  repository: pravega/zookeeper
  tag: 0.2.15
  pullPolicy: IfNotPresent

triggerRollingRestart: false

domainName:
labels: {}
ports: []
  # - containerPort: 2181
  #   name: client
  # - containerPort: 2888
  #   name: quorum
  # - containerPort: 8080
  #   name: admin-server
  # - containerPort: 7000
  #   name: metrics
kubernetesClusterDomain: "cluster.local"
probes:
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 10
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 10
pod:
  # labels: {}
  # nodeSelector: {}
  # affinity: {}
  # topologySpreadConstraints: {}
  # resources: {}
  # tolerations: []
  # env: []
  # annotations: {}
  # securityContext: {}
  # terminationGracePeriodSeconds: 30
  serviceAccountName: zookeeper
  # imagePullSecrets: []

adminServerService: {}
  # annotations: {}
  # external: false

clientService: {}
  # annotations: {}

headlessService: {}
  # annotations: {}

config:
  # initLimit: 10
  # tickTime: 2000
  # syncLimit: 2
  # globalOutstandingLimit: 1000
  preAllocSize: 16384 # default 65536
  # snapCount: 100000
  # commitLogCount: 500
  # snapSizeLimitInKb: 4194304
  # maxCnxns: 0
  # maxClientCnxns: 60
  # minSessionTimeout: 4000
  # maxSessionTimeout: 40000
  # autoPurgeSnapRetainCount: 3
  # autoPurgePurgeInterval: 1
  # quorumListenOnAllIPs: false
  # additionalConfig: {}

## configure the storage type
## accepted values : persistence/ephemeral
## default option is persistence
storageType: persistence

persistence:
  storageClassName:
  ## specifying reclaim policy for PersistentVolumes
  ## accepted values - Delete / Retain
  reclaimPolicy: Delete
  annotations: {}
  volumeSize: 20Gi

ephemeral:
  emptydirvolumesource:
    ## specifying Medium for emptydirvolumesource
    ## accepted values - ""/Memory
    medium: ""
    sizeLimit: 20Gi

hooks:
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.23.2
    securityContext: {}
    #  runAsUser: 1001
    #  runAsGroup: 1001
  backoffLimit: 10
  pod:
    annotations: {}

containers: []
volumes: []
volumeMounts: []
initContainers: []
